Traditional chinese
seattleflu/lab-result-reports pull request #6
Opened 2020-04-28 04:38 UTC by kairstenfay

Add traditional Chinese (zh-Hant) report translation.
Update external links to use translations where available.

2020-04-28 04:40 UTC, kairstenfay commented
![](https://github.trello.services/images/mini-trello-icon.png) [New language: Traditional Chinese](https://trello.com/c/x10272OV/552-new-language-traditional-chinese)

2020-04-28 05:13 UTC, kairstenfay commented
![](https://github.trello.services/images/mini-trello-icon.png) ["never tested" for all languages](https://trello.com/c/WnW5D614/555-never-tested-for-all-languages)

2020-04-28 22:46 UTC, tsibley approved these changes
LGTM assuming our language reviewers give the thumbs up. The updates to existing templates will require us to manually trigger a whole new PDF regen on the backoffice, yeah?

2020-04-28 22:51 UTC, joverlee521 requested changes
I would definitely recommend increasing the font size for traditional Chinese. Even I have squint to read it with the current font size.

2020-04-29 00:59 UTC, kairstenfay commented
> LGTM assuming our language reviewers give the thumbs up. The updates to existing templates will require us to manually trigger a whole new PDF regen on the backoffice, yeah?

We're pending review now. 

Yes, someone will have to manually create new PDFs for zh-Hant. This task is tracked in the Trello card.

2020-04-29 01:00 UTC, kairstenfay commented
> I would definitely recommend increasing the font size for traditional Chinese. Even I have squint to read it with the current font size.

Thank you for this feedback!

2020-04-29 20:07 UTC, kairstenfay commented
`zh-Hant` now has a working bold-face font (thanks for catching this, @joverlee521 !). Unfortunately this required the download of Noto Sans CJK fonts which, on my machine, slows down the Docker image generation by about 2 minutes.

2020-04-29 20:09 UTC, kairstenfay commented
I just force-pushed after rewording a commit. No code changes.

2020-04-30 01:10 UTC, kairstenfay commented
Just pushed a new commit with downloaded Chinese fonts in the `fonts` directory. The Docker image is no longer burdened by downloading the huge Noto CJK package.

2020-04-30 01:13 UTC, kairstenfay commented
I just force-pushed a reword and a minor whitespace edit. I don't intend to make further changes at this time.

2020-05-05 03:28 UTC, kairstenfay commented
The zh-Hant report has been verified by a native speaker.

2020-05-05 03:29 UTC, merged

2020-05-05 18:46 UTC, tsibley reviewed
Somehow I never submitted the comments below. Just found them because discussion in Slack triggered my memory. Submitting now for posterity, even though this PR is merged already.

2020-05-05 18:46 UTC, tsibley commented on scan/report-zh-Hans.tex
> +  Path        = /output/fonts/,
Hardcoding this Path means there's now a hard requirement on a `/output` mount and no chance of this working outside of Docker. I think instead the font files could be copied into the Docker image and referred to by a relative path in these templates.

2020-05-05 18:46 UTC, tsibley commented on scan/report-zh-Hans.tex
> +  Path        = /output/fonts/,
Thinking about this a bit more: we're using Noto Sans CJK now for Simplified Chinese, Traditional Chinese, and in the future (presumably) Korean. That just leaves Japanese as the only language which is in the larger `fonts-noto-cjk` package but that we won't use, so maybe the returns are dwindling.

I think the only remaining win might be if individual PDF generation (not Docker image generation) is faster when TeX only has to load the single-language font files. Not sure about this.